### ISSUE TITLE
A few feature suggestions

### ISSUE THREAD

**Issue by thunder-red-star** [stuyDevs/homework#2]
1. I'm not sure how this is happening, can you fix this?
    ![image](https://user-images.githubusercontent.com/67127399/160620141-1bd39b00-8945-4086-800f-da239cb6a4b7.png)

2. Multiple uploads to same path gives cryptic error (I'm too lazy to fork your HW server to see how it works)
    ![image](https://user-images.githubusercontent.com/67127399/160620302-6336ac3e-ce17-443c-adeb-5860d90096c0.png)

3. Remove the first line from the submission when added to Github so file is runnable

**Comment by srijal30** [comment]
you can have comments so number 3 is not a concern. Not experienced with javascript so not really sure how to fix the first 2 :(
